server:
  port: 8769
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuwudeqi/springcloud_for_noob.git # 配置git仓库的地址
          search-paths: config-repo                              # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: wuwudeqi                              # git仓库的账号
          password: fu.ai102                              # git密码
    stream:
      kafka:
        binder:
          brokers: localhost:9092
    bus:
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
